# Generated by Django 5.0.2 on 2026-02-20 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_locked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceactivity',
            name='device_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.devicetag'),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='service_type',
            field=models.CharField(choices=[('SIM_REG', 'SIM Registration'), ('SIM_SWAP', 'SIM Swap'), ('SIM_RET', 'SIM Retrieval'), ('NIN_LINK', 'NIN Linking'), ('MIFI', 'MiFi Sale')], max_length=20),
        ),
    ]
