# Generated by Django 5.0.2 on 2026-02-21 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_serviceactivity_device_tag_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='servicetarget',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='servicetarget',
            name='device_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.devicetag'),
        ),
        migrations.AlterField(
            model_name='servicetarget',
            name='service_type',
            field=models.CharField(choices=[('SIM_REG', 'SIM Registration'), ('SIM_SWAP', 'SIM Swap'), ('SIM_UPGRADE', 'SIM Upgrade'), ('GOTV', 'GOTV Subscription'), ('DSTV', 'DSTV Subscription')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='servicetarget',
            unique_together={('branch', 'service_type', 'device_tag', 'date')},
        ),
    ]
