# Generated by Django 5.0.2 on 2026-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_servicetarget_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceactivity',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='serviceactivity',
            name='requires_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
    ]
