# Generated by Django 5.0.2 on 2026-02-27 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_product_description_product_imei_last_5_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
