# Generated by Django 5.0.2 on 2026-02-27 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('package_type', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('NEW', 'New Subscription'), ('RENEWAL', 'Renewal'), ('UPGRADE', 'Upgrade')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='MultiChoiceActivity',
        ),
    ]
