# Generated by Django 5.0.2 on 2026-03-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_product_imei_last_5_product_imei_serial_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='retailsale',
            index=models.Index(fields=['date'], name='core_retail_date_1b32aa_idx'),
        ),
        migrations.AddIndex(
            model_name='retailsale',
            index=models.Index(fields=['branch'], name='core_retail_branch__f5443e_idx'),
        ),
        migrations.AddIndex(
            model_name='retailsale',
            index=models.Index(fields=['staff'], name='core_retail_staff_i_14e004_idx'),
        ),
    ]
