# Generated by Django 5.0.2 on 2026-03-08 20:43

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_retailsale_core_retail_date_1b32aa_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='allowed_radius',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='location_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance_from_branch', models.FloatField(default=0)),
                ('selfie', models.ImageField(upload_to='attendance_selfies/')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_late', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
