# Generated by Django 5.0.2 on 2026-03-10 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_branch_allowed_radius_branch_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='allowed_radius',
            field=models.IntegerField(default=300),
        ),
        migrations.CreateModel(
            name='DirectorSafeStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Director Safe Stock',
            },
        ),
    ]
