# Generated by Django 5.0.2 on 2026-03-15 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_branch_allowed_radius_directorsafestock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultiChoiceBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('weekly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_history', to='core.multichoiceweeklyreport')),
            ],
            options={
                'ordering': ['-date', '-time'],
            },
        ),
    ]
