# Generated by Django 5.0.2 on 2026-04-02 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_multichoicesale_customer_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='multichoicebalance',
            name='is_commission_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_detected', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_detected', models.DateTimeField(auto_now_add=True)),
                ('date_paid', models.DateField(blank=True, null=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('balance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.multichoicebalance')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
