# Generated by Django 5.0.2 on 2026-04-03 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_multichoicebalance_is_commission_payment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_balance', models.IntegerField(default=0)),
                ('current_month', models.IntegerField(default=0)),
                ('current_year', models.IntegerField(default=0)),
                ('total_received', models.IntegerField(default=0)),
                ('total_sold', models.IntegerField(default=0)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sim_inventory', to='core.branch')),
            ],
        ),
        migrations.CreateModel(
            name='SimInventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('OPENING', 'Opening Balance'), ('RECEIVED', 'SIM Received'), ('SOLD', 'SIM Sold/Used')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.siminventory')),
            ],
        ),
    ]
