# Generated by Django 5.0.2 on 2026-04-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_supplier_retailsale_is_voided_retailsale_void_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceactivity',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceactivity',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='serviceactivity',
            name='customer_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
