# Generated by Django 5.0.2 on 2026-05-08 00:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_serviceactivity_customer_name_serviceactivity_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetarget',
            name='customer_phone',
        ),
        migrations.CreateModel(
            name='WholesaleDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_type', models.CharField(choices=[('SIM', 'SIM Card'), ('MIFI', 'MiFi Device'), ('ROUTER', 'Router'), ('OTHER', 'Other Device')], default='MIFI', max_length=10)),
                ('network_type', models.CharField(choices=[('4G', '4G LTE'), ('5G', '5G'), ('ANY', 'Any/Not Applicable')], default='4G', max_length=5)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_devices', to='core.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='WholesaleDeviceSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_type', models.CharField(choices=[('CUSTOMER', 'Customer'), ('DIRECTOR', 'Director'), ('BRANCH', 'Branch Transfer')], default='CUSTOMER', max_length=10)),
                ('buyer_name', models.CharField(blank=True, max_length=200)),
                ('buyer_phone', models.CharField(blank=True, max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('TRANSFER', 'Transfer'), ('POS', 'POS')], default='CASH', max_length=20)),
                ('is_director_sale', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='core.wholesaledevice')),
                ('sold_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='wholesaledevice',
            index=models.Index(fields=['branch', 'staff'], name='core_wholes_branch__b961f7_idx'),
        ),
    ]
