# Generated by Django 5.0.2 on 2026-05-25 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_add_invoice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
