# Generated by Django 5.0.2 on 2026-06-12 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_loyaltypoint_loyaltytransaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(default='auto', max_length=50)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partial')], max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_recipient', models.EmailField(blank=True, max_length=254)),
                ('email_error', models.TextField(blank=True)),
                ('supabase_uploaded', models.BooleanField(default=False)),
                ('supabase_error', models.TextField(blank=True)),
                ('record_count', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectorDailyDigest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_recipient', models.EmailField(blank=True, max_length=254)),
                ('email_error', models.TextField(blank=True)),
                ('total_retail_sales', models.IntegerField(default=0)),
                ('total_retail_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_multichoice_sales', models.IntegerField(default=0)),
                ('total_multichoice_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_service_activities', models.IntegerField(default=0)),
                ('total_new_customers', models.IntegerField(default=0)),
                ('total_stock_alerts', models.IntegerField(default=0)),
                ('total_attendance_records', models.IntegerField(default=0)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VOID', 'Voided'), ('SALE', 'Sale Recorded'), ('STOCK_IN', 'Stock Added'), ('STOCK_OUT', 'Stock Released'), ('PRICE_CHANGE', 'Price Changed'), ('CHECK_IN', 'Checked In'), ('CHECK_OUT', 'Checked Out'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('BACKUP', 'Backup Run'), ('RESET', 'Monthly Reset')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'timestamp'], name='core_change_model_n_623447_idx'), models.Index(fields=['action', 'timestamp'], name='core_change_action_1ab7a3_idx'), models.Index(fields=['branch', 'timestamp'], name='core_change_branch__978303_idx')],
            },
        ),
        migrations.CreateModel(
            name='MonthlyResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('reset_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('reset_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PriceFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_floors', to='core.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_floors', to='core.product')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('product', 'branch')},
            },
        ),
    ]
