# Generated by Django 5.0.2 on 2026-06-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_backuplog_directordailydigest_changelog_and_more'),
    ]

    operations = [
    ]
