# Generated by Django 5.0.2 on 2026-06-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_add_product_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, help_text='Product color variant', max_length=50, null=True),
        ),
    ]
