# Generated by Django 5.0.2 on 2026-07-04 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_product_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon e.g. 📱', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catalog Category',
                'verbose_name_plural': 'Catalog Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SlideShowItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='slideshow/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an external image URL')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. NEW, HOT DEAL, LIMITED', max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Original price before discount', max_digits=12, null=True)),
                ('cta_text', models.CharField(default='Order on WhatsApp', help_text='Button text', max_length=50)),
                ('whatsapp_msg', models.TextField(blank=True, help_text='Pre-filled WhatsApp message. Leave blank to auto-generate.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Slideshow Item',
                'verbose_name_plural': 'Slideshow Items',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/')),
                ('image_url', models.URLField(blank=True, help_text='Or paste an external image URL')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('badge', models.CharField(blank=True, help_text='e.g. HOT, NEW, SOLD OUT', max_length=50)),
                ('condition', models.CharField(choices=[('NEW', 'Brand New'), ('UK', 'UK Used'), ('LOCAL', 'Nigerian Used')], default='NEW', max_length=10)),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured section')),
                ('whatsapp_msg', models.TextField(blank=True, help_text='Pre-filled WhatsApp message. Leave blank to auto-generate.')),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='core.catalogcategory')),
            ],
            options={
                'verbose_name': 'Catalog Product',
                'verbose_name_plural': 'Catalog Products',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
