# Generated by Django 5.0.2 on 2026-07-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_multichoice_expiry_router_sub'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multichoicesale',
            name='expiry_date',
        ),
        migrations.AlterField(
            model_name='routersubscription',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Auto-set to subscription_date + 30 days', null=True),
        ),
        migrations.AlterField(
            model_name='routersubscription',
            name='month_number',
            field=models.PositiveIntegerField(default=1, help_text='1 = first month, 2 = second month'),
        ),
        migrations.AlterField(
            model_name='routersubscription',
            name='subscription_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
