# Generated by Django 5.0.2 on 2026-07-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_add_stock_transfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailsale',
            name='color',
            field=models.CharField(blank=True, help_text='Color variant sold', max_length=50, null=True),
        ),
    ]
