# Generated by Django 5.0.2 on 2026-08-07 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_retailsale_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlineSaleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Name of product/service sold', max_length=200)),
                ('customer_name', models.CharField(max_length=150)),
                ('customer_phone', models.CharField(max_length=20)),
                ('platform', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('twitter', 'Twitter/X'), ('referral', 'Referral'), ('other', 'Other')], default='whatsapp', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sale_date', models.DateField()),
                ('evidence_image', models.ImageField(blank=True, help_text='Screenshot or photo evidence of sale', null=True, upload_to='online_sales/')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_verified', models.BooleanField(default=False, help_text='Director/Manager verified this sale')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_sales', to='core.branch')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='online_sales', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_online_sales', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Online Sale Log',
                'verbose_name_plural': 'Online Sale Logs',
                'ordering': ['-sale_date', '-created_at'],
            },
        ),
    ]
