from django.urls import path
from . import views

urlpatterns = [
    path('', views.custom_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('staff/', views.staff_dashboard, name='staff_dashboard'),
    path('telecom/', views.staff_dashboard, name='telecom_dashboard'),
    path('manager/', views.manager_dashboard, name='manager_dashboard'),
    path('director/', views.director_dashboard, name='director_dashboard'),
    path('retail/', views.retail_dashboard, name='retail_dashboard'),
    path('multichoice/', views.multichoice_dashboard, name='multichoice_dashboard'),
    path('approve/<int:activity_id>/', views.approve_activity, name='approve_activity'),
    path('add-stock-safe/', views.add_stock_to_safe, name='add_stock_to_safe'),
    path('release-stock/', views.release_stock, name='release_stock'),
    path('record-sale/', views.record_retail_sale, name='record_retail_sale'),
    path('record-multichoice/', views.record_multichoice_sale, name='record_multichoice_sale'),
    path('multichoice/start-week/', views.start_weekly_report, name='start_weekly_report'),
    path('multichoice/close-week/', views.close_weekly_report, name='close_weekly_report'),
    path('staff-create-product/', views.staff_create_product, name='staff_create_product'),
    path('add-category/', views.add_category, name='add_category'),
    path('record-expense/', views.record_expense, name='record_expense'),
    path('request-stock/', views.request_stock, name='request_stock'),
    path('approve-stock-request/<int:request_id>/', views.approve_stock_request, name='approve_stock_request'),
    path('branch-report-pdf/<int:branch_id>/', views.generate_branch_report_pdf, name='generate_branch_report_pdf'),
    path('export-report/', views.export_branch_report, name='export_branch_report'),
    path('attendance/', views.check_in, name='check_in'),
    path('attendance/history/', views.attendance_history, name='attendance_history'),
    path('director/attendance/', views.director_attendance_dashboard, name='director_attendance_dashboard'),
    path('director/manage-locations/', views.manage_branch_locations, name='manage_branch_locations'),
    path('director/safe/', views.director_safe_stock, name='director_safe_stock'),
    path('director/safe/add/', views.add_director_stock, name='add_director_stock'),
    path('director/safe/delete/<int:stock_id>/', views.delete_director_stock, name='delete_director_stock'),
    path('director/safe/create-product/', views.create_director_product, name='create_director_product'),
    path('product-catalog/', views.product_catalog, name='product_catalog'),
    path('record-physical-product/', views.record_physical_product, name='record_physical_product'),
    path('attendance/export-pdf/', views.export_monthly_attendance_pdf, name='export_monthly_attendance_pdf'),
    path('record-balance/', views.record_balance, name='record_balance'),
    path('upload-stock-csv/', views.upload_stock_csv, name='upload_stock_csv'),
    path('customer-crm/', views.customer_crm, name='customer_crm'),
    path('stock-alerts/', views.stock_alerts, name='stock_alerts'),
    path('staff-checkout/<int:staff_id>/', views.staff_checkout, name='staff_checkout'),
    path('staff-checkin/<int:staff_id>/', views.staff_checkin, name='staff_checkin'),
    path('add-device-commission/', views.add_device_commission, name='add_device_commission'),
]
